version: '3.8'

services:
  web:
    image: ${REGISTRY}/${APP_NAME_IMAGE}:latest
    container_name: ${APP_NAME}
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
